language: erlang

env:
  global:
    - LUAROCKS=2.2.0
    - LUAODBC_TEST_DBMS=MySQL
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

branches:
  only:
    - master
    - gcc44

before_install:
  - bash .travis/setup_lua.sh
  - sudo pip install cpp-coveralls
  - sudo luarocks install luacov-coveralls
  - mysql --version
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - sudo apt-get install libmyodbc libsqliteodbc unixodbc unixodbc-dev
  - sudo odbcinst -i -d -f /usr/share/libmyodbc/odbcinst.ini
  - sudo odbcinst -i -s -l -f ./test/mytest.odbc.ini
  - sudo luarocks install lunitx

install:
  - sudo luarocks make rockspec/odbc-scm-0.rockspec CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage";
  - lua -e "odbc=require'odbc';odbc.environment():drivers(print)"
  - lua -e "odbc=require'odbc';odbc.environment():datasources(print)"

script:
  - cd test/dba
  - lunit.sh test.lua
  - cd .. 
  - lunit.sh test.lua
  - lua luasql/test-luasql.lua

after_success:
  - coveralls -b .. -r .. --dump c.report.json
  - luacov-coveralls -j c.report.json

notifications:
  email:
    on_success: change
    on_failure: always
